### ISSUE TITLE
how to add pic by json

### ISSUE THREAD

**Issue by Zephery** [codecrafting-net/chromagallery#10]
hello，how to add pic by json？

**Comment by codecrafting-io** [comment]
First, sorry for taking a long time to answer that, currently I have little time to support this project, but early next year I will go back with a lot of new things and a proper release. To your question, there's is no way to provide a url json to load automatically the images, but you can do something like this:

```js
        var jsonObj = {
        items:
        [
            {
                src: 'images/thumbs/1.jpg',
                alt:'Pic 1',
                largesrc:'images/1.jpg'    
            },
            {
                src: 'images/thumbs/2.jpg',
                alt:'Pic 2',
                largesrc:'images/2.jpg'    
            },
            {
                src: 'images/thumbs/3.jpg',
                alt:'Pic 3',
                largesrc:'images/3.jpg'    
            },
            {
                src: 'images/thumbs/4.jpg',
                alt:'Pic 4',
                largesrc:'images/4.jpg'    
            }
        ]
    };
    $(".mygallery").chromaGallery(jsonObj);
```

But if you want to add a image to a already loaded gallery, this feature is yet to be implemented. I will consider loading multiples images with jsonObj. 

Thanks.
